//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestChatEntities : DbContext
    {
        public TestChatEntities()
            : base("name=TestChatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Connection> Connection { get; set; }
        public virtual DbSet<Chatting> Chatting { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
    }
}
