//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NumNews { get; set; }
        public string Content { get; set; }
        public string Time { get; set; }
        public byte[] Pic { get; set; }
        public string username { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
