//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.News = new HashSet<News>();
            this.Reports = new HashSet<Reports>();
        }
    
        public string name { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public Nullable<bool> sexsual { get; set; }
        public Nullable<int> height { get; set; }
        public string location { get; set; }
        public string education { get; set; }
        public string bio { get; set; }
        public byte[] avt { get; set; }
        public byte[] pic1 { get; set; }
        public byte[] pic2 { get; set; }
        public byte[] pic3 { get; set; }
        public byte[] pic4 { get; set; }
        public byte[] pic5 { get; set; }
        public string username { get; set; }
        public string fav { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports> Reports { get; set; }
    }
}
